[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 静的解析
repo = 'scrooloose/syntastic'

[[plugins]] # ドキュメント参照
repo = 'thinca/vim-ref'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'

[[plugins]] # html
repo = 'mattn/emmet-vim'

[[plugins]] # show indent level
repo = 'Yggdroot/indentLine'

[[plugins]] # file system explorer
repo = 'scrooloose/nerdtree'

[[plugins]] # vim motion on speed
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'zchee/deoplete-clang'

[[plugins]]
repo = 'Shougo/neco-syntax'
