[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 静的解析
repo = 'scrooloose/syntastic'

[[plugins]] # ドキュメント参照
repo = 'thinca/vim-ref'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'

[[plugins]] # html
repo = 'mattn/emmet-vim'

[[plugins]] # show indent level
repo = 'Yggdroot/indentLine'

[[plugins]] # file system explorer
repo = 'scrooloose/nerdtree'

[[plugins]] # vim motion on speed
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'
on_ft = ['ruby']

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_fy = ['julia']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c']

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
