[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # コード補完
repo = 'Shougo/neocomplcache.vim'
repo = 'Shougo/neocomplcache-rsense.vim'

[[plugins]] # 静的解析
repo = 'scrooloose/syntastic'

[[plugins]] # ドキュメント参照
repo = 'thinca/vim-ref'
repo = 'yuku-t/vim-ref-ri'

[[plugins]] # メソッドの定義元へジャンプ
repo = 'szw/vim-tags'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'
